# Generated by Django 5.2.17 on 2026-09-02 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_address", models.CharField(max_length=255)),
                (
                    "current_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "current_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("pickup_address", models.CharField(max_length=255)),
                (
                    "pickup_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("delivery_address", models.CharField(max_length=255)),
                (
                    "delivery_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "current_cycle_used_hrs",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(70),
                        ],
                    ),
                ),
                (
                    "total_distance_miles",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "total_duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "route_polyline",
                    models.JSONField(
                        blank=True,
                        help_text="Route path as [[lat, lng], ...]",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
