# Generated by Django 5.2.17 on 2026-09-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="total_trip_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calendar hours from trip start to end (includes rests and stops).",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DutySegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Order of this segment in the trip timeline (0-based)."
                    ),
                ),
                (
                    "duty_status",
                    models.CharField(
                        choices=[
                            ("off_duty", "Off duty"),
                            ("sleeper", "Sleeper berth"),
                            ("driving", "Driving"),
                            ("on_duty", "On duty (not driving)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("pickup", "Pickup"),
                            ("delivery", "Delivery"),
                            ("fuel", "Fuel"),
                            ("rest", "Rest"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                (
                    "miles_at_start",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "miles_at_end",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_segments",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip_id", "sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "sequence"), name="unique_trip_segment_sequence"
                    )
                ],
            },
        ),
    ]
