# Generated by Django 5.2.17 on 2026-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_total_trip_hours_dutysegment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="route_polyline",
        ),
        migrations.AddField(
            model_name="trip",
            name="route_to_delivery_polyline",
            field=models.JSONField(
                blank=True,
                help_text="Route from pickup to delivery as [[lat, lng], ...].",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="route_to_pickup_polyline",
            field=models.JSONField(
                blank=True,
                help_text="Route from current location to pickup as [[lat, lng], ...].",
                null=True,
            ),
        ),
    ]
